name: CI/CD Pipeline - GitHub Actions

on:
  push:
    branches:
      - '*'
  pull_request:
    branches: [ develop, homolog, master ]

jobs:
  deploying_into_develop:
    if: github.ref == 'refs/heads/develop'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Merge to develop branch
        run: git merge develop
      - name: Push to develop branch
        run: |
          git push origin develop
          echo "Deploying to Development..."
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  deploying_into_staging:
    if: github.ref == 'refs/heads/homolog'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Merge to homolog branch
        run: git merge homolog
      - name: Push to homolog branch
        run: |
          git push origin homolog
          echo "Deploying to Staging..."
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  deploying_into_production:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Merge to master branch
        run: git merge master
      - name: Push to master branch
        run: |
          git push origin master
          echo "Deploying to Production..."
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
